spring:
  profiles:
    active: development
  # 关闭Spring Boot艺术字
  main:
    banner-mode: "off"


---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/edm_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: edm
    password: edmpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 自动加载sql文件
    schema:
       - classpath:sql/edm_zone.sql
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  # 开发环境下将缓存关闭
  thymeleaf:
    cache: false
---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://172.16.11.4:3306/edm_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: hive
    password: Passw0rd
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
