spring:
  profiles:
    active: development
  # 关闭Spring Boot艺术字
  main:
    banner-mode: "off"
  # 发送邮件
  mail:
    host: smtp.wo.cn
    port: 25
    username: shuju@wo.cn
    password: shu@ju#2019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # rabbitmq 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    rabbitmq 的消息确认
#    publisher-returns: true
#    publisher-confirms: true
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/edm_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: edm
    password: edmpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 自动加载sql文件
    schema:
       - classpath:sql/edm_zone.sql
       - classpath:sql/edm_target_description.sql
       - classpath:sql/edmers.sql
       - classpath:sql/edm_roles.sql
       - classpath:sql/edmer_role_relation.sql
       - classpath:sql/qunfa_business.sql
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  # 开发环境下将缓存关闭
  thymeleaf:
    cache: false
---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://172.16.11.4:3306/edm_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: hive
    password: Passw0rd
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
